### ISSUE TITLE
grafeas.io: Custom Search Engine is scoped to istio.io, not grafeas.io

### ISSUE THREAD

**Issue by rionam** [Grafeas/issues#1]
**Is this a BUG or FEATURE REQUEST?:**
Bug

**Did you review existing epics and issues to identify if this already being worked on?** (please try to add the correct labels and epics):
No other existing bugs

**What happened**:
Every search returns results from istio.io. Searching for strings in the grafeas docs returns no results.

**What you expected to happen:**
Search box would return results scoped to grafeas.io

**How to reproduce it:**
on grafeas.io, search for "grafeas". Result: search results are form istio
search for 

Now copy a string from any page on the site and search. For example: "An occurrence can be thought of as an instantiation of a note"
Expected: Return https://grafeas.io/docs/concepts/what-is-grafeas/overview.html
Result: No results.

**Feature Request:**
N
**Describe the feature and user story:**

**Comment by vtsao** [comment]
Wendy can you TAL?

**Comment by R2wenD2** [comment]
This is fixed now, although the search results are opening in a new window, which is not ideal. I'm going to keep this open until I address that too.

**Comment by aysylu** [comment]
Closing this since we're unlikely to change the display of the search results as overlay in the near or mid-term, and we'd like to consolidate all the resources.
